DEBUG 2016-08-08 17:52:15,281: 	 Executing command: 'submit'
DEBUG 2016-08-08 17:52:15,282: 	 Found CRAB cache file /afs/cern.ch/user/m/mhaapale/.crab3
DEBUG 2016-08-08 17:52:15,331: 	 Checking credentials
DEBUG 2016-08-08 17:52:15,332: 	 Proxy file /tmp/x509up_u93770 not found
DEBUG 2016-08-08 17:52:15,332: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
ERROR 2016-08-08 17:52:16,118: 	 Keyboard Interrupted
DEBUG 2016-08-08 17:52:55,496: 	 Executing command: 'submit'
DEBUG 2016-08-08 17:52:55,497: 	 Found CRAB cache file /afs/cern.ch/user/m/mhaapale/.crab3
DEBUG 2016-08-08 17:52:55,505: 	 Checking credentials
DEBUG 2016-08-08 17:52:55,506: 	 Found proxy file /tmp/x509up_u93770
DEBUG 2016-08-08 17:52:55,506: 	 Getting proxy life time left
DEBUG 2016-08-08 17:52:56,013: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u93770 -timeleft
 output : 86374

 error: 
 retcode : 0
DEBUG 2016-08-08 17:52:56,519: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u93770 -actimeleft
 output : 86373

 error: 
 retcode : 0
DEBUG 2016-08-08 17:52:56,519: 	 Proxy valid for 23:59:34 hours
INFO 2016-08-08 17:52:56,521: 	 Will use CRAB configuration file Tuples/crabConfig_data.py
DEBUG 2016-08-08 17:52:56,521: 	 Loading CRAB configuration file.
DEBUG 2016-08-08 17:52:56,525: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-08-08 17:52:56,525: 	 Working area '/afs/cern.ch/work/m/mhaapale/public/CMSSW_5_3_32/src/cms-opendata-2011-jets/AnalysisFW/python/crab_projects/crab_OpenDataTree_all' already exists 
Please change the requestName in the config file
ERROR 2016-08-08 17:52:56,525: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1607.patch2/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/m/mhaapale/public/CMSSW_5_3_32/src/cms-opendata-2011-jets/AnalysisFW/python/crab_projects/crab_OpenDataTree_all' already exists 
Please change the requestName in the config file
